let data = [
  {    
    image: "./assets/image/abay.jpg",
    image_zoom: "/assets/image/abay2.PNG",    
    title: "Zulkifli",
    nim: '3312201069',
    jabatan: "Ketua Kelas",
    quotes:'Quotes belum diisi',
  },
  {
    image: "./assets/image/sephira.jpg",
    image_zoom: "/assets/image/sephira.jpg",    
    title: "Sephira",
    nim: '3312201075',
    jabatan: "Wakil ketua Kelas",
    quotes:'Quotes belum diisi',
  },
  {
    image: "./assets/image/hadi.jpg",
    image_zoom: "/assets/image/hadi2.jpg",    
    title: "Nurhadi",
    nim: '3312201082',
    jabatan: "Anggota Kelas",    
    quotes:
      "Mau siapapun presidennya , kalau kamu ga kerja ya kamu miskin",
  },
  {
    image: "./assets/image/noviati.jpg",
    image_zoom:"",
    title: "Noviati Saliha",
    nim: '3312201076',
    jabatan: "Anggota Kelas",
    quotes:'Quotes belum diisi',
  },
  {
    image: "./assets/image/jessica.jpg",
    image_zoom:"",
    title: "Jessica Intan Kinasih",
    nim: '3312201063',
    jabatan: "Anggota Kelas",
    quotes:'Quotes belum diisi',
  },
  {
    image: "./assets/image/hery.jpeg",
    image_zoom:"",
    title: "Hery Swando Sinaga",
    nim: '3312201085',
    jabatan: "Anggota Kelas",
    quotes:'Quotes belum diisi',
  },
  {
    image: "./assets/image/hugo.jpg",
    image_zoom:"/assets/image/hugo3.jpg",
    title: "Hugo Hamonangan",
    nim: '3312201066',
    jabatan: "Anggota Kelas",
    quotes:'Apabila ikhtiar dan doa telah dilaksanakan, disitulah rahmat Allah akan dilimpahkan',
  },
  {    
    image: "./assets/image/sherina.jpg",
    image_zoom:"/assets/image/sherina2.jpeg",
    title: "Sherina Nur Syabania",
    nim: '3312201078',
    jabatan: "Anggota Kelas",
    quotes:'Quotes belum diisi',
  },
  {
    image: "./assets/image/dhea.jpg",
    image_zoom:"",
    title: "Dhea Salsabila Yustin",
    nim: '3312201065',
    jabatan: "Anggota Kelas",
    quotes:'Quotes belum diisi',
  },
  {    
    image: "./assets/image/afif.jpeg",
    image_zoom: "/assets/image/afif2.jpg",    
    title: "Rizqi Ammar Afif",
    nim: '3312201084',
    jabatan: "Anggota Kelas",
    quotes:'Quotes belum diisi',
  },
  {
    image: "./assets/image/athallah.jpg",
    image_zoom:"",
    title: "M. Rizki Putro Athallah",
    nim: '3312201074',
    jabatan: "Anggota Kelas",
    quotes:'Quotes belum diisi',
  },
  {
    image: "./assets/image/hairul.jpg",
    image_zoom:"",
    title: "Hairul Anwar Salfindi",
    nim: '3312201089',
    jabatan: "Anggota Kelas",
    quotes:'Quotes belum diisi',
  },
  {
    image: "./assets/image/rido.jpg",
    image_zoom:"",
    title: "Rido Wahyu Tambunan",
    nim: '3312201070',
    jabatan: "Anggota Kelas",
    quotes:'Quotes belum diisi',
  },
  {
    image: "./assets/image/rahmad.jpeg",
    image_zoom:"",
    title: "Rahmad Kurniawan",
    nim: '3312201073',
    jabatan: "Anggota Kelas",
    quotes:'Quotes belum diisi',
  },
  {
    image: "./assets/image/janrianto.jfif",
    image_zoom:"",
    title: "Janrianto Rizki",
    nim: '3312201077',
    jabatan: "Anggota Kelas",
    quotes:'Quotes belum diisi',
  },
  {
    image: "./assets/image/thariq.jpg",
    image_zoom:"",
    title: "M. farhan Thariq",
    nim: '3312201072',
    jabatan: "Anggota Kelas",
    quotes:'Quotes belum diisi',
  },
  {
    image: "./assets/image/aulia.jpg",
    image_zoom:"",
    title: "Aulia Nabila Husnah",
    nim: '3312201088',
    jabatan: "Anggota Kelas",
    quotes:'Quotes belum diisi',
  },
  {
    image: "./assets/image/anggi.jpg",
    image_zoom:"",
    title: "Anggi Eunika Simanjuntak",
    nim: '3312201087',
    jabatan: "Anggota Kelas",
    quotes:'Quotes belum diisi',
  },
  {
    image: "./assets/image/josefhin.jpg",
    image_zoom:"",
    title: "Josefhin Apryanto",
    nim: '3312201081',
    jabatan: "Anggota Kelas",
    quotes:'Quotes belum diisi',
  },
  {
    image: "./assets/image/feni.jpg",
    image_zoom:"",
    title: "Feni Debora Siregar",
    nim: '3312201086',
    jabatan: "Anggota Kelas",
    quotes:'Quotes belum diisi',
  },
  {
    image: "./assets/image/fitri.jpeg",
    image_zoom:"",
    title: "Fitri Rahmadilla",
    nim: '3312201080',
    jabatan: "Anggota Kelas",
    quotes:'Quotes belum diisi',
  },
  {
    image: "./assets/image/yazid.jpeg",
    image_zoom:"",
    title: "Muhammad Yazid Al Farisy",
    nim: '3312201079',
    jabatan: "Anggota Kelas",
    quotes:'Quotes belum diisi',
  },
  {
    image: "./assets/image/andre.jpg",
    image_zoom:"",
    title: "Andre Prasasti",
    nim: '3312201083',
    jabatan: "Anggota Kelas",
    quotes:'Quotes belum diisi',
  },
  {
    image: "./assets/image/fatimah.jpeg",
    image_zoom:"",
    title: "Fatimah Azzahra",
    nim: '3312201071',
    jabatan: "Anggota Kelas",
    quotes:'Quotes belum diisi',
  },
  {
    image: "./assets/image/abdillah.jpg",
    image_zoom:"",
    title: "M Abdillah",
    nim: '3312201080',
    jabatan: "Anggota Kelas",
    quotes:'Quotes belum diisi',
  },
  {
    image: "./assets/image/ihsan.jpg",
    image_zoom:"",
    title: "Muhammad Ihsan Nabawi",
    nim: '3312201068',
    jabatan: "Anggota Kelas",
    quotes:'Quotes belum diisi',
  },
  {    
    image: "./assets/image/febriadi.jfif",
    image_zoom: "/assets/image/febriadi2.jpeg",    
    title: "Febriadi Lesmana",
    nim: '3312201062',
    jabatan: "Anggota Kelas",
    quotes:'Tak perlu seseorang yang sempurna, cukup temukan orang yang membuatmu lebih bahagia dan membuatmu berarti lebih dari siapapun',
  },
  {
    image: "./assets/image/balqis.jpg",
    image_zoom:"",
    title: "Nabila Arisya Balqis",
    nim: '3312201090',
    jabatan: "Anggota Kelas",
    quotes:'Quotes belum diisi',
  },
];

let mydata = data.sort((d1, d2) => (d1.nim > d2.nim)? 1 : (d1.nim <d2.nim)? -1 : 0);